version: '2'
services:
    handson001-app:
        image: handson001
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://handson001-mysql:3306/handson001?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    handson001-mysql:
        extends:
            file: mysql.yml
            service: handson001-mysql
